### ISSUE TITLE
跟写controllers 有什么差别？

### ISSUE THREAD

**Issue by yaobo-lab** [Meowv/Plus.AutoApi#1]
跟写controllers 有什么差别？ 能提高了什么开发效率？还不是要写 WeatherService

**Comment by Meowv** [comment]
面向DDD开发模式，如果你的项目全部在controller里面写业务逻辑肯定是没有必要的。

**Comment by yaobo-lab** [comment]
> 面向DDD开发模式，如果你的项目全部在controller里面写业务逻辑肯定是没有必要的。

不会将逻辑写controller里的；每个模块一个Service ； Service 注入controller 使用；  你这是将Service 跟Controller 两个结合在一起的意思？

**Comment by Meowv** [comment]
> Service 注入controller 使用；

你可以简单理解目的就是减少这一步操作，用来动态创建api的。
